version: "3.4"
services:

  # PHP-FPM
  #=============================================================================
  app:
    tty: true
    ports:
      - "9000:9000"

  # DATABASE
  #=============================================================================
  db:
    tty: true
    ports:
      - "3306:3306"
