version: "3.4"
services:

  # APPLICATION
  #=============================================================================
  app:
    tty: true
    ports:
      - "9000:9000"

  # NGINX Server
  #=============================================================================
  webserver:
    restart: always
    ports:
      - "80:80"

  # DATABASE
  #=============================================================================
  db:
    restart: always
    tty: true
    ports:
      - "${DB_PORT}:${DB_PORT}"
