version: "3.4"
services:

  # APPLICATION
  #=============================================================================
  app:
    env_file:
      - ./.env
    tty: true
    ports:
      - "9000:9000"
    command: >
      bash -c "composer install --prefer-dist --no-dev --optimize-autoloader --no-interaction\
      && php index.php"

  # NGINX Server
  #=============================================================================
  webserver:
    ports:
      - "80:80"

  # DATABASE
  #=============================================================================
  db:
    tty: true
    ports:
      - "${DB_PORT}:${DB_PORT}"
