version: "3.4"
services:

  # APPLICATION
  #=============================================================================
  app:
    build:
      context: ./docker
      dockerfile: app/Dockerfile
      args:
        - APP_PHP_VERSION=${PHP_VERSION}
        - APP_SYS_USER_ID=${SYS_USER_ID}
        - APP_SYS_GROUP_ID=${SYS_GROUP_ID}
        - APP_NODE_JS_VERSION=${NODE_JS_VERSION}
    container_name: swoole-chatter-app
    networks:
      - app-network
    volumes:
      - ./src:/var/www/swoole-chatter
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
#    command: >
#      bash -c "composer install --prefer-dist --no-progress --no-suggest && php index.php"

  # NGINX Server
  #=============================================================================
  webserver:
    image: nginx:alpine
    container_name: swoole-chatter-webserver
    restart: unless-stopped
    links:
      - app
    depends_on:
      - app
    networks:
      - app-network
    working_dir: /var/www/swoole-chatter
    volumes:
      - ./src/public:/var/www/swoole-chatter
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/app.conf

  # DATABASE
  #=============================================================================
  db:
    image: mysql:5.7.22
    container_name: swoole-chatter-db
    restart: unless-stopped
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/db/install.sh:/install.sh
      - ./docker/db/setup.sql:/setup.sql
      - db-data:/var/lib/mysql
    networks:
      - app-network

# DOCKER NETWORKS
#===============================================================================
networks:
  app-network:
    driver: bridge

# DOCKER VOLUMES
#===============================================================================
volumes:
  db-data:
    driver: local
