name: Deployment

# Trigger events
#=============================================================================
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps of the pipeline
    #==========================================================================
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOYMENT_HOST }}
          username: ${{ secrets.DEPLOYMENT_USER }}
          password: ${{ secrets.DEPLOYMENT_PASSWORD }}
          port: ${{ secrets.DEPLOYMENT_PORT }}
          script: |
            cd ${{ secrets.DEPLOYMENT_PROJECT_PATH }}

            echo "Pull code"
            echo "============================================================================="
            git pull origin master

            echo "Build container"
            echo "============================================================================="
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build --force-recreate

            echo "Install dependencies"
            echo "============================================================================="
            docker-compose exec -T --user www app composer install --prefer-dist --no-dev --optimize-autoloader --no-interaction
            docker-compose exec -T --user www app npm install

            echo "Start swoole server"
            echo "============================================================================="
            docker-compose exec -T --user www app php index.php

            echo "Build frontend"
            echo "============================================================================="
            docker-compose exec -T --user www app npm run prod
