name: Integration

# Trigger events
#=============================================================================
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    # Environment variables
    #==========================================================================
    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      SYS_USER_ID: ${{ secrets.SYS_USER_ID }}
      SYS_GROUP_ID: ${{ secrets.SYS_GROUP_ID }}

      PHP_VERSION: 7.4
      NODE_JS_VERSION: 14
      APP_SERVER_PORT: ${{ secrets.APP_SERVER_PORT }}

    # Steps of the pipeline
    #==========================================================================
    steps:
      - uses: actions/checkout@v2

      - name: Environment info
        run: docker-compose --version

      - name: Validate docker config
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.test.yml config

      - name: Build docker
        if: success()
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.test.yml up -d --build

      - name: Validate composer config
        if: success()
        run: docker-compose exec -T --user www app composer validate

      - name: Install dependencies
        if: success()
        run: |
          docker-compose exec -T --user www app \
          composer install --prefer-dist --no-suggest

      - name: Start swoole server
        if: success()
        run: |
          docker-compose exec -T --user www app php index.php

      - name: Check code quality (Sniffer)
        if: success()
        run: |
          docker-compose exec -T --user www app \
          ./vendor/bin/phpcs

      - name: Run static analysis (Psalm)
        if: success()
        run: |
          docker-compose exec -T --user www app \
          ./vendor/bin/psalm --show-info=false

      - name: Run PHP tests
        run: |
          docker-compose exec -T --user www app \
          ./vendor/bin/phpunit --filter MessageTest --testdox
